import asyncio
import logging
from app.agents.data_engineer import DataEngineerAgent
from app.core.state import PortfolioState
import json

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

async def test_data_engineer():
    logger.info("Initializing Data Engineer Test...")
    
    # 1. Initialize Agent
    agent = DataEngineerAgent()
    
    # 2. Setup Test State
    test_state: PortfolioState = {
        "date": "2026-03-18",
        "universe": ["AAPL", "MSFT"], # Keep it small for testing
        "iterations": 0,
        "raw_data": {},
        "alpha_signals": {},
        "target_weights": {},
        "backtest_metrics": {},
        "is_validated": False,
        "final_weights": {}
    }
    
    logger.info("Running Data Engineer Agent...")
    try:
        # 3. Execute Agent (This will hit yfinance, FMP, SEC EDGAR, and Redis)
        result_state = await agent.run(test_state)
        
        # 4. Verify Output
        raw_data = result_state.get("raw_data", {})
        if "error" in raw_data:
            logger.error(f"Pipeline Failed: {raw_data['error']}")
            return
            
        metadata = raw_data.get("metadata", {})
        
        logger.info("\n=== TEST RESULTS ===")
        logger.info(f"LLM Status: {metadata.get('status')}")
        logger.info(f"Imputation Strategy: {metadata.get('imputation_strategy')}")
        logger.info(f"Anomalies: {metadata.get('anomalies')}")
        logger.info(f"Summary generated by LLM: {metadata.get('summary')}")
        
        # Check data shapes
        closes = raw_data.get("close_prices", {})
        returns = raw_data.get("log_returns", {})
        if closes:
            logger.info(f"Successfully ingested and aligned {len(closes)} symbols.")
            sample_ticker = list(closes.keys())[0]
            logger.info(f"{sample_ticker} price data points: {len(closes[sample_ticker])}")
            logger.info(f"{sample_ticker} return data points: {len(returns[sample_ticker])}")
            
    except Exception as e:
        logger.error(f"Test script encountered a critical failure: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    asyncio.run(test_data_engineer())
